### ISSUE TITLE
TypeError: isinstance expected 2 arguments, got 1

### ISSUE THREAD

**Issue by qria** [Stewori/pytypes#46]
Running [Usage example with decorator](https://github.com/Stewori/pytypes#usage-example-with-decorator) in readme gave following error for me.

```
Traceback (most recent call last):
  File "/tmp/tmp.py", line 31, in <module>
    pytypes.dump_cache()
NameError: name 'pytypes' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 316, in _dump_module
    assumed_glbls, implicit_globals, assumed_typevars)
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 755, in dump
    assumed_globals, implicit_globals, assumed_typevars)
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 680, in dump
    assumed_globals, implicit_globals))
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 653, in _stub_src_annotations
    assumed_globals, implicit_globals), ' ...']
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 625, in _declaration
    if annotated else self._signature(), ':'))
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 597, in _annotated_signature
    tp_lst = _prepare_arg_types_list(combine_argtype(self.arg_type_observations),
  File "/Users/qria/.venvs/jupyter2/lib/python3.6/site-packages/pytypes/typelogger.py", line 149, in combine_argtype
    assert isinstance(is_Tuple(observations[0]))
TypeError: isinstance expected 2 arguments, got 1
```

I don't know much about this codebase but maybe you've intended `assert is_Tuple(observations[0])`? 

versions:

pytypes==1.0b4

**Comment by Stewori** [comment]
Yes that's true. This was overlooked during refactoring towards Python 3.7 support. Can you check if this change fixes it? Sorry that tests did not uncover this. They need to be improved. I am currently on vacation and have only a mobile device. So I cannot check it myself. This will have high priority as soon as I'm back. However feel free to post a pr.

**Comment by qria** [comment]
Sure thing. I'll submit a PR.
