### ISSUE TITLE
Error when checking a tuple against a typing.List

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#48]
```python
>>> from pytypes import type_util
>>> import typing
>>> type_util._isinstance((), typing.List)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 2 must be a class or tuple of classes
>>> type_util._isinstance((), typing.List[typing.Any])
```

**Comment by Stewori** [comment]
AFAIK () does not produce an empty tuple. Try (, ).

**Comment by mitar** [comment]
I think it does.

```
>>> type(())
<class 'tuple'>
>>> len(())
0
```

`(,)` is invalid syntax.

**Comment by Stewori** [comment]
Okay. Anyway, it shouldn't raise an exception. Does it work with Sequence? I suspect this originates again from List being invariant. I'm currently on vacation only with mobile device. I will look into this as soon as I'm back. Unless you find a fix until then...

**Comment by Stewori** [comment]
As pointed out in #49, please share a full stcktrace with pytypes trace cleaning disabled.

**Comment by mitar** [comment]
I have found a workaround for my needs, so this is not critical.

**Comment by mitar** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1870, in _isinstance
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1740, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1769, in _issubclass_2
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1262, in _issubclass_Generic
    return issubclass(typing.Sequence, superclass.__origin__)
TypeError: issubclass() arg 2 must be a class or tuple of classes
```
