### ISSUE TITLE
Exception: Parameterized generics cannot be used with class or instance checks

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#56]
Reproduction:

```python
import typing
import pytypes
from pytypes import type_util

type_util._issubclass(typing.List[typing.Dict[str, str]], typing.List[dict])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pytypes/type_util.py", line 1769, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../pytypes/type_util.py", line 1799, in _issubclass_2
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../pytypes/type_util.py", line 1345, in _issubclass_Generic
    _recursion_check):
  File ".../pytypes/type_util.py", line 1769, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../pytypes/type_util.py", line 1796, in _issubclass_2
    _recursion_check)
  File ".../pytypes/type_util.py", line 1140, in _issubclass_Mapping_covariant
    return issubclass(subclass, superclass)
  File "/usr/lib/python3.6/typing.py", line 1148, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks
```

Using pytypes-1.0b5.

**Comment by mitar** [comment]
Still true on `pytypes-1.0b5.post18`.

I got another one:

```python
from typing import *
import pytypes
from pytypes import type_util

pytypes.enable_clean_traceback(False)

type_util._issubclass(type(None), Optional[Dict[str, Any]])
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1898, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1911, in _issubclass_2
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1643, in _issubclass_Union
    bound_typevars_readonly, False, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1675, in _issubclass_Union_rec
    for t in super_args)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1675, in <genexpr>
    for t in super_args)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1898, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1925, in _issubclass_2
    _recursion_check)
  File ".../lib/python3.6/site-packages/pytypes/type_util.py", line 1259, in _issubclass_Mapping_covariant
    return issubclass(subclass, superclass)
  File "/usr/lib/python3.6/typing.py", line 1148, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks
```

**Comment by Stewori** [comment]
I could simplify the reproduction of the original error, i.e. independently from List:
```
type_util._issubclass(dict, typing.Dict[str, str])
```
produces the same error. I think that's the core issue. (Didn't look at the issue with ``Optional`` yet)

**Comment by Stewori** [comment]
The second one fails in a rather similar manner, also reproducible independently from its `Optional`-surrounding:

```
type_util._issubclass(type(None), typing.Dict[str, str])
```

Looks like I should revisit `_issubclass_Mapping_covariant`.

**Comment by mitar** [comment]
Thanks!
