### ISSUE TITLE
is_of_type([], List[int]) throws an exception in 3.7

### ISSUE THREAD

**Issue by mooncake4132** [Stewori/pytypes#59]
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> import pytypes
>>> pytypes.is_of_type([], typing.List[int])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1904, in _isinstance
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1769, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1799, in _issubclass_2
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1310, in _issubclass_Generic
    bound_typevars_readonly, follow_fwd_refs, _recursion_check):
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1769, in _issubclass
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1799, in _issubclass_2
    bound_typevars_readonly, follow_fwd_refs, _recursion_check)
  File "D:\.virtualenvs\pytypes\lib\site-packages\pytypes\type_util.py", line 1293, in _issubclass_Generic
    if subclass.__origin__ is None:
AttributeError: type object 'Empty' has no attribute '__origin__'
```
This seems to be related to #32. I tested the above in python 3.6.5 and it worked fine, so it's only an issue in python 3.7.

**Comment by mooncake4132** [comment]
Just noticed this is not python 3.7 ready yet #40 . Closing this issue.
