### ISSUE TITLE
OrderedDict is treated as incompatible with Mapping

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#66]
The following code:
```python3
from collections import OrderedDict
from typing import Mapping

from pytypes import TypeChecker

def f() -> Mapping[int, str]:
    return OrderedDict()

with TypeChecker():
    f()
```
fails as follows:
```python3
$ python3 Test.py 
Traceback (most recent call last):
  File "Test.py", line 11, in <module>
    f()
  File "Test.py", line 8, in f
    return OrderedDict()
pytypes.exceptions.ReturnTypeError: 
  __main__.f
  returned incompatible type:
Expected: Mapping[int, str]
Received: OrderedDict
```
```

**Comment by Stewori** [comment]
`OrderedDict` is currently not supported. I don't really want to add new features before Python 3.7 compatibility is achieved. I can see if adding this support is somewhat trivial. Otherwise this has to be postponed.
