### ISSUE TITLE
Empty dict is incompatible with Mapping

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#68]
The following code:
```python3
from typing import List, Mapping

from pytypes import TypeChecker

def f() -> List[Mapping[int, str]]:
    return [{}]

with TypeChecker():
    f()
    print("OK")
```
fails as follows:
```python3
$ python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    f()
  File "Test.py", line 6, in f
    return [{}]
pytypes.exceptions.ReturnTypeError: 
  __main__.f
  returned incompatible type:
Expected: List[Mapping[int, str]]
Received: List[Empty[Dict]]
```

**Comment by Stewori** [comment]
Does this also occur when not wrapped in a `List`?
Otherwise I suspect the answer from https://github.com/Stewori/pytypes/issues/67#issuecomment-524914412 applies here as well.

**Comment by jolaf** [comment]
No, it doesn't occur when not wrapped in a `List`.

**Comment by Stewori** [comment]
Closing this in favor of #76.
