### ISSUE TITLE
List[function] is incompatible with List[Callable]

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#70]
The following code:
```python3
from typing import Callable, List

from pytypes import TypeChecker

def n() -> None:
    pass

def f() -> List[Callable[[], None]]:
    return [n]

with TypeChecker():
    f()
    print("OK")
```
fails as follows:
```python3
$ python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 12, in <module>
    f()
  File "Test.py", line 9, in f
    return [n]
pytypes.exceptions.ReturnTypeError: 
  __main__.f
  returned incompatible type:
Expected: List[Callable[[], NoneType]]
Received: List[function]
```

**Comment by Stewori** [comment]
Again: Does this also occur when not wrapped in a `List`?
Otherwise I suspect the answer from https://github.com/Stewori/pytypes/issues/67#issuecomment-524914412 applies here as well.

**Comment by jolaf** [comment]
No, it doesn't occur when not wrapped in a `List`.

**Comment by Stewori** [comment]
Closing this in favor of #76.
