### ISSUE TITLE
Type[] annotation is not handled correctly

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#73]
The following code:
```python3
from typing import Type

from pytypes import TypeChecker

def f() -> Type[str]:
    return str

with TypeChecker():
    f()
    print("OK")
```
fails as follows:
```python3
$ python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 9, in <module>
    f()
  File "Test.py", line 6, in f
    return str
pytypes.exceptions.ReturnTypeError: 
  __main__.f
  returned incompatible type:
Expected: Type[str]
Received: type
```

**Comment by Stewori** [comment]
Looks like `deep_type` doesn't support type. This might be reasonably easy to add...
